### ISSUE TITLE
Target API Key

### ISSUE THREAD

**Issue by JadeP27** [jonnahmarie/Project-1-Basix#6]
How do we get the API Key?
What are the limitations?
What do we request?
What is the api response?

**Comment by jonnahmarie** [comment]
How do we get the API Key?
- Someone would have to have a Rapid API account in order to receive a key.

What are the limitations?
- The free 'Basic' plan has a hard limit of 50 requests/month. Upgrading to the next plan would cost $19.99/month and I don't know if anyone would want to front that amount.

What do we request?
- Store Location and Product Details

What is the api response?
- For the Target Store Location Search:
`location_id`
- For the Target Product Details:
`avail_ratio` (?)
`title`
`images`

**Comment by vtaymany** [comment]
Meeting 11/14/2020:

The limitations make this API unusable for our case.
